before_install:
  - gem update --system 2.1.11
  - gem --version
rvm:
  - 2.0.0
  - 2.1.0
script: 'bundle exec rake spec'
env:
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 4.3.0"
matrix:
  exclude:
    # No support for Ruby 2.0 before Puppet 3.2
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
